// Generated by the protocol buffer compiler.  DO NOT EDIT!

package smarkets.eto;

public final class EtoPiqi {
  private EtoPiqi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum PayloadType
      implements com.google.protobuf.ProtocolMessageEnum {
    PAYLOAD_NONE(0, 1),
    PAYLOAD_PING(1, 2),
    PAYLOAD_PONG(2, 3),
    PAYLOAD_GAPFILL(3, 4),
    PAYLOAD_HEARTBEAT(4, 5),
    PAYLOAD_REPLAY(5, 6),
    PAYLOAD_LOGIN(6, 7),
    PAYLOAD_LOGIN_RESPONSE(7, 8),
    PAYLOAD_LOGOUT(8, 9),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static PayloadType valueOf(int value) {
      switch (value) {
        case 1: return PAYLOAD_NONE;
        case 2: return PAYLOAD_PING;
        case 3: return PAYLOAD_PONG;
        case 4: return PAYLOAD_GAPFILL;
        case 5: return PAYLOAD_HEARTBEAT;
        case 6: return PAYLOAD_REPLAY;
        case 7: return PAYLOAD_LOGIN;
        case 8: return PAYLOAD_LOGIN_RESPONSE;
        case 9: return PAYLOAD_LOGOUT;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<PayloadType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PayloadType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PayloadType>() {
            public PayloadType findValueByNumber(int number) {
              return PayloadType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return smarkets.eto.EtoPiqi.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final PayloadType[] VALUES = {
      PAYLOAD_NONE, PAYLOAD_PING, PAYLOAD_PONG, PAYLOAD_GAPFILL, PAYLOAD_HEARTBEAT, PAYLOAD_REPLAY, PAYLOAD_LOGIN, PAYLOAD_LOGIN_RESPONSE, PAYLOAD_LOGOUT, 
    };
    public static PayloadType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private PayloadType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      smarkets.eto.EtoPiqi.getDescriptor();
    }
  }
  
  public enum LogoutReason
      implements com.google.protobuf.ProtocolMessageEnum {
    LOGOUT_NONE(0, 1),
    LOGOUT_HEARTBEAT_TIMEOUT(1, 2),
    LOGOUT_CONFIRMATION(2, 3),
    LOGOUT_LOGIN_TIMEOUT(3, 4),
    LOGOUT_LOGIN_NOT_FIRST_SEQ(4, 5),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static LogoutReason valueOf(int value) {
      switch (value) {
        case 1: return LOGOUT_NONE;
        case 2: return LOGOUT_HEARTBEAT_TIMEOUT;
        case 3: return LOGOUT_CONFIRMATION;
        case 4: return LOGOUT_LOGIN_TIMEOUT;
        case 5: return LOGOUT_LOGIN_NOT_FIRST_SEQ;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<LogoutReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LogoutReason>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogoutReason>() {
            public LogoutReason findValueByNumber(int number) {
              return LogoutReason.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return smarkets.eto.EtoPiqi.getDescriptor().getEnumTypes().get(1);
    }
    
    private static final LogoutReason[] VALUES = {
      LOGOUT_NONE, LOGOUT_HEARTBEAT_TIMEOUT, LOGOUT_CONFIRMATION, LOGOUT_LOGIN_TIMEOUT, LOGOUT_LOGIN_NOT_FIRST_SEQ, 
    };
    public static LogoutReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private LogoutReason(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      smarkets.eto.EtoPiqi.getDescriptor();
    }
  }
  
  public static final class Payload extends
      com.google.protobuf.GeneratedMessage {
    // Use Payload.newBuilder() to construct.
    private Payload() {}
    
    private static final Payload defaultInstance = new Payload();
    public static Payload getDefaultInstance() {
      return defaultInstance;
    }
    
    public Payload getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Payload_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Payload_fieldAccessorTable;
    }
    
    // required uint64 seq = 1;
    public static final int SEQ_FIELD_NUMBER = 1;
    private boolean hasSeq;
    private long seq_ = 0L;
    public boolean hasSeq() { return hasSeq; }
    public long getSeq() { return seq_; }
    
    // optional .smarkets.eto.PayloadType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private boolean hasType;
    private smarkets.eto.EtoPiqi.PayloadType type_ = smarkets.eto.EtoPiqi.PayloadType.PAYLOAD_NONE;
    public boolean hasType() { return hasType; }
    public smarkets.eto.EtoPiqi.PayloadType getType() { return type_; }
    
    // optional bool is_replay = 3 [default = false];
    public static final int IS_REPLAY_FIELD_NUMBER = 3;
    private boolean hasIsReplay;
    private boolean isReplay_ = false;
    public boolean hasIsReplay() { return hasIsReplay; }
    public boolean getIsReplay() { return isReplay_; }
    
    // optional .smarkets.eto.Replay replay = 4;
    public static final int REPLAY_FIELD_NUMBER = 4;
    private boolean hasReplay;
    private smarkets.eto.EtoPiqi.Replay replay_ = smarkets.eto.EtoPiqi.Replay.getDefaultInstance();
    public boolean hasReplay() { return hasReplay; }
    public smarkets.eto.EtoPiqi.Replay getReplay() { return replay_; }
    
    // optional .smarkets.eto.Login login = 5;
    public static final int LOGIN_FIELD_NUMBER = 5;
    private boolean hasLogin;
    private smarkets.eto.EtoPiqi.Login login_ = smarkets.eto.EtoPiqi.Login.getDefaultInstance();
    public boolean hasLogin() { return hasLogin; }
    public smarkets.eto.EtoPiqi.Login getLogin() { return login_; }
    
    // optional .smarkets.eto.LoginResponse login_response = 6;
    public static final int LOGIN_RESPONSE_FIELD_NUMBER = 6;
    private boolean hasLoginResponse;
    private smarkets.eto.EtoPiqi.LoginResponse loginResponse_ = smarkets.eto.EtoPiqi.LoginResponse.getDefaultInstance();
    public boolean hasLoginResponse() { return hasLoginResponse; }
    public smarkets.eto.EtoPiqi.LoginResponse getLoginResponse() { return loginResponse_; }
    
    // optional .smarkets.eto.Logout logout = 7;
    public static final int LOGOUT_FIELD_NUMBER = 7;
    private boolean hasLogout;
    private smarkets.eto.EtoPiqi.Logout logout_ = smarkets.eto.EtoPiqi.Logout.getDefaultInstance();
    public boolean hasLogout() { return hasLogout; }
    public smarkets.eto.EtoPiqi.Logout getLogout() { return logout_; }
    
    public final boolean isInitialized() {
      if (!hasSeq) return false;
      if (hasReplay()) {
        if (!getReplay().isInitialized()) return false;
      }
      if (hasLogin()) {
        if (!getLogin().isInitialized()) return false;
      }
      if (hasLoginResponse()) {
        if (!getLoginResponse().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSeq()) {
        output.writeUInt64(1, getSeq());
      }
      if (hasType()) {
        output.writeEnum(2, getType().getNumber());
      }
      if (hasIsReplay()) {
        output.writeBool(3, getIsReplay());
      }
      if (hasReplay()) {
        output.writeMessage(4, getReplay());
      }
      if (hasLogin()) {
        output.writeMessage(5, getLogin());
      }
      if (hasLoginResponse()) {
        output.writeMessage(6, getLoginResponse());
      }
      if (hasLogout()) {
        output.writeMessage(7, getLogout());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSeq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getSeq());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, getType().getNumber());
      }
      if (hasIsReplay()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getIsReplay());
      }
      if (hasReplay()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getReplay());
      }
      if (hasLogin()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getLogin());
      }
      if (hasLoginResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getLoginResponse());
      }
      if (hasLogout()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getLogout());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static smarkets.eto.EtoPiqi.Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smarkets.eto.EtoPiqi.Payload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private smarkets.eto.EtoPiqi.Payload result;
      
      // Construct using smarkets.eto.EtoPiqi.Payload.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new smarkets.eto.EtoPiqi.Payload();
        return builder;
      }
      
      protected smarkets.eto.EtoPiqi.Payload internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new smarkets.eto.EtoPiqi.Payload();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smarkets.eto.EtoPiqi.Payload.getDescriptor();
      }
      
      public smarkets.eto.EtoPiqi.Payload getDefaultInstanceForType() {
        return smarkets.eto.EtoPiqi.Payload.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public smarkets.eto.EtoPiqi.Payload build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private smarkets.eto.EtoPiqi.Payload buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public smarkets.eto.EtoPiqi.Payload buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        smarkets.eto.EtoPiqi.Payload returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smarkets.eto.EtoPiqi.Payload) {
          return mergeFrom((smarkets.eto.EtoPiqi.Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smarkets.eto.EtoPiqi.Payload other) {
        if (other == smarkets.eto.EtoPiqi.Payload.getDefaultInstance()) return this;
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasIsReplay()) {
          setIsReplay(other.getIsReplay());
        }
        if (other.hasReplay()) {
          mergeReplay(other.getReplay());
        }
        if (other.hasLogin()) {
          mergeLogin(other.getLogin());
        }
        if (other.hasLoginResponse()) {
          mergeLoginResponse(other.getLoginResponse());
        }
        if (other.hasLogout()) {
          mergeLogout(other.getLogout());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSeq(input.readUInt64());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              smarkets.eto.EtoPiqi.PayloadType value = smarkets.eto.EtoPiqi.PayloadType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                setType(value);
              }
              break;
            }
            case 24: {
              setIsReplay(input.readBool());
              break;
            }
            case 34: {
              smarkets.eto.EtoPiqi.Replay.Builder subBuilder = smarkets.eto.EtoPiqi.Replay.newBuilder();
              if (hasReplay()) {
                subBuilder.mergeFrom(getReplay());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setReplay(subBuilder.buildPartial());
              break;
            }
            case 42: {
              smarkets.eto.EtoPiqi.Login.Builder subBuilder = smarkets.eto.EtoPiqi.Login.newBuilder();
              if (hasLogin()) {
                subBuilder.mergeFrom(getLogin());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLogin(subBuilder.buildPartial());
              break;
            }
            case 50: {
              smarkets.eto.EtoPiqi.LoginResponse.Builder subBuilder = smarkets.eto.EtoPiqi.LoginResponse.newBuilder();
              if (hasLoginResponse()) {
                subBuilder.mergeFrom(getLoginResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginResponse(subBuilder.buildPartial());
              break;
            }
            case 58: {
              smarkets.eto.EtoPiqi.Logout.Builder subBuilder = smarkets.eto.EtoPiqi.Logout.newBuilder();
              if (hasLogout()) {
                subBuilder.mergeFrom(getLogout());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLogout(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // required uint64 seq = 1;
      public boolean hasSeq() {
        return result.hasSeq();
      }
      public long getSeq() {
        return result.getSeq();
      }
      public Builder setSeq(long value) {
        result.hasSeq = true;
        result.seq_ = value;
        return this;
      }
      public Builder clearSeq() {
        result.hasSeq = false;
        result.seq_ = 0L;
        return this;
      }
      
      // optional .smarkets.eto.PayloadType type = 2;
      public boolean hasType() {
        return result.hasType();
      }
      public smarkets.eto.EtoPiqi.PayloadType getType() {
        return result.getType();
      }
      public Builder setType(smarkets.eto.EtoPiqi.PayloadType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = smarkets.eto.EtoPiqi.PayloadType.PAYLOAD_NONE;
        return this;
      }
      
      // optional bool is_replay = 3 [default = false];
      public boolean hasIsReplay() {
        return result.hasIsReplay();
      }
      public boolean getIsReplay() {
        return result.getIsReplay();
      }
      public Builder setIsReplay(boolean value) {
        result.hasIsReplay = true;
        result.isReplay_ = value;
        return this;
      }
      public Builder clearIsReplay() {
        result.hasIsReplay = false;
        result.isReplay_ = false;
        return this;
      }
      
      // optional .smarkets.eto.Replay replay = 4;
      public boolean hasReplay() {
        return result.hasReplay();
      }
      public smarkets.eto.EtoPiqi.Replay getReplay() {
        return result.getReplay();
      }
      public Builder setReplay(smarkets.eto.EtoPiqi.Replay value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasReplay = true;
        result.replay_ = value;
        return this;
      }
      public Builder setReplay(smarkets.eto.EtoPiqi.Replay.Builder builderForValue) {
        result.hasReplay = true;
        result.replay_ = builderForValue.build();
        return this;
      }
      public Builder mergeReplay(smarkets.eto.EtoPiqi.Replay value) {
        if (result.hasReplay() &&
            result.replay_ != smarkets.eto.EtoPiqi.Replay.getDefaultInstance()) {
          result.replay_ =
            smarkets.eto.EtoPiqi.Replay.newBuilder(result.replay_).mergeFrom(value).buildPartial();
        } else {
          result.replay_ = value;
        }
        result.hasReplay = true;
        return this;
      }
      public Builder clearReplay() {
        result.hasReplay = false;
        result.replay_ = smarkets.eto.EtoPiqi.Replay.getDefaultInstance();
        return this;
      }
      
      // optional .smarkets.eto.Login login = 5;
      public boolean hasLogin() {
        return result.hasLogin();
      }
      public smarkets.eto.EtoPiqi.Login getLogin() {
        return result.getLogin();
      }
      public Builder setLogin(smarkets.eto.EtoPiqi.Login value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLogin = true;
        result.login_ = value;
        return this;
      }
      public Builder setLogin(smarkets.eto.EtoPiqi.Login.Builder builderForValue) {
        result.hasLogin = true;
        result.login_ = builderForValue.build();
        return this;
      }
      public Builder mergeLogin(smarkets.eto.EtoPiqi.Login value) {
        if (result.hasLogin() &&
            result.login_ != smarkets.eto.EtoPiqi.Login.getDefaultInstance()) {
          result.login_ =
            smarkets.eto.EtoPiqi.Login.newBuilder(result.login_).mergeFrom(value).buildPartial();
        } else {
          result.login_ = value;
        }
        result.hasLogin = true;
        return this;
      }
      public Builder clearLogin() {
        result.hasLogin = false;
        result.login_ = smarkets.eto.EtoPiqi.Login.getDefaultInstance();
        return this;
      }
      
      // optional .smarkets.eto.LoginResponse login_response = 6;
      public boolean hasLoginResponse() {
        return result.hasLoginResponse();
      }
      public smarkets.eto.EtoPiqi.LoginResponse getLoginResponse() {
        return result.getLoginResponse();
      }
      public Builder setLoginResponse(smarkets.eto.EtoPiqi.LoginResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginResponse = true;
        result.loginResponse_ = value;
        return this;
      }
      public Builder setLoginResponse(smarkets.eto.EtoPiqi.LoginResponse.Builder builderForValue) {
        result.hasLoginResponse = true;
        result.loginResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginResponse(smarkets.eto.EtoPiqi.LoginResponse value) {
        if (result.hasLoginResponse() &&
            result.loginResponse_ != smarkets.eto.EtoPiqi.LoginResponse.getDefaultInstance()) {
          result.loginResponse_ =
            smarkets.eto.EtoPiqi.LoginResponse.newBuilder(result.loginResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginResponse_ = value;
        }
        result.hasLoginResponse = true;
        return this;
      }
      public Builder clearLoginResponse() {
        result.hasLoginResponse = false;
        result.loginResponse_ = smarkets.eto.EtoPiqi.LoginResponse.getDefaultInstance();
        return this;
      }
      
      // optional .smarkets.eto.Logout logout = 7;
      public boolean hasLogout() {
        return result.hasLogout();
      }
      public smarkets.eto.EtoPiqi.Logout getLogout() {
        return result.getLogout();
      }
      public Builder setLogout(smarkets.eto.EtoPiqi.Logout value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLogout = true;
        result.logout_ = value;
        return this;
      }
      public Builder setLogout(smarkets.eto.EtoPiqi.Logout.Builder builderForValue) {
        result.hasLogout = true;
        result.logout_ = builderForValue.build();
        return this;
      }
      public Builder mergeLogout(smarkets.eto.EtoPiqi.Logout value) {
        if (result.hasLogout() &&
            result.logout_ != smarkets.eto.EtoPiqi.Logout.getDefaultInstance()) {
          result.logout_ =
            smarkets.eto.EtoPiqi.Logout.newBuilder(result.logout_).mergeFrom(value).buildPartial();
        } else {
          result.logout_ = value;
        }
        result.hasLogout = true;
        return this;
      }
      public Builder clearLogout() {
        result.hasLogout = false;
        result.logout_ = smarkets.eto.EtoPiqi.Logout.getDefaultInstance();
        return this;
      }
    }
    
    static {
      smarkets.eto.EtoPiqi.getDescriptor();
    }
    
    static {
      smarkets.eto.EtoPiqi.internalForceInit();
    }
  }
  
  public static final class Replay extends
      com.google.protobuf.GeneratedMessage {
    // Use Replay.newBuilder() to construct.
    private Replay() {}
    
    private static final Replay defaultInstance = new Replay();
    public static Replay getDefaultInstance() {
      return defaultInstance;
    }
    
    public Replay getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Replay_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Replay_fieldAccessorTable;
    }
    
    // required uint64 seq = 1;
    public static final int SEQ_FIELD_NUMBER = 1;
    private boolean hasSeq;
    private long seq_ = 0L;
    public boolean hasSeq() { return hasSeq; }
    public long getSeq() { return seq_; }
    
    public final boolean isInitialized() {
      if (!hasSeq) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSeq()) {
        output.writeUInt64(1, getSeq());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSeq()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getSeq());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static smarkets.eto.EtoPiqi.Replay parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Replay parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smarkets.eto.EtoPiqi.Replay prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private smarkets.eto.EtoPiqi.Replay result;
      
      // Construct using smarkets.eto.EtoPiqi.Replay.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new smarkets.eto.EtoPiqi.Replay();
        return builder;
      }
      
      protected smarkets.eto.EtoPiqi.Replay internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new smarkets.eto.EtoPiqi.Replay();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smarkets.eto.EtoPiqi.Replay.getDescriptor();
      }
      
      public smarkets.eto.EtoPiqi.Replay getDefaultInstanceForType() {
        return smarkets.eto.EtoPiqi.Replay.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public smarkets.eto.EtoPiqi.Replay build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private smarkets.eto.EtoPiqi.Replay buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public smarkets.eto.EtoPiqi.Replay buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        smarkets.eto.EtoPiqi.Replay returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smarkets.eto.EtoPiqi.Replay) {
          return mergeFrom((smarkets.eto.EtoPiqi.Replay)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smarkets.eto.EtoPiqi.Replay other) {
        if (other == smarkets.eto.EtoPiqi.Replay.getDefaultInstance()) return this;
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setSeq(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required uint64 seq = 1;
      public boolean hasSeq() {
        return result.hasSeq();
      }
      public long getSeq() {
        return result.getSeq();
      }
      public Builder setSeq(long value) {
        result.hasSeq = true;
        result.seq_ = value;
        return this;
      }
      public Builder clearSeq() {
        result.hasSeq = false;
        result.seq_ = 0L;
        return this;
      }
    }
    
    static {
      smarkets.eto.EtoPiqi.getDescriptor();
    }
    
    static {
      smarkets.eto.EtoPiqi.internalForceInit();
    }
  }
  
  public static final class Login extends
      com.google.protobuf.GeneratedMessage {
    // Use Login.newBuilder() to construct.
    private Login() {}
    
    private static final Login defaultInstance = new Login();
    public static Login getDefaultInstance() {
      return defaultInstance;
    }
    
    public Login getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Login_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Login_fieldAccessorTable;
    }
    
    // required string session = 1;
    public static final int SESSION_FIELD_NUMBER = 1;
    private boolean hasSession;
    private java.lang.String session_ = "";
    public boolean hasSession() { return hasSession; }
    public java.lang.String getSession() { return session_; }
    
    public final boolean isInitialized() {
      if (!hasSession) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSession()) {
        output.writeString(1, getSession());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSession()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSession());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static smarkets.eto.EtoPiqi.Login parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Login parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smarkets.eto.EtoPiqi.Login prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private smarkets.eto.EtoPiqi.Login result;
      
      // Construct using smarkets.eto.EtoPiqi.Login.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new smarkets.eto.EtoPiqi.Login();
        return builder;
      }
      
      protected smarkets.eto.EtoPiqi.Login internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new smarkets.eto.EtoPiqi.Login();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smarkets.eto.EtoPiqi.Login.getDescriptor();
      }
      
      public smarkets.eto.EtoPiqi.Login getDefaultInstanceForType() {
        return smarkets.eto.EtoPiqi.Login.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public smarkets.eto.EtoPiqi.Login build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private smarkets.eto.EtoPiqi.Login buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public smarkets.eto.EtoPiqi.Login buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        smarkets.eto.EtoPiqi.Login returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smarkets.eto.EtoPiqi.Login) {
          return mergeFrom((smarkets.eto.EtoPiqi.Login)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smarkets.eto.EtoPiqi.Login other) {
        if (other == smarkets.eto.EtoPiqi.Login.getDefaultInstance()) return this;
        if (other.hasSession()) {
          setSession(other.getSession());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setSession(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string session = 1;
      public boolean hasSession() {
        return result.hasSession();
      }
      public java.lang.String getSession() {
        return result.getSession();
      }
      public Builder setSession(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSession = true;
        result.session_ = value;
        return this;
      }
      public Builder clearSession() {
        result.hasSession = false;
        result.session_ = getDefaultInstance().getSession();
        return this;
      }
    }
    
    static {
      smarkets.eto.EtoPiqi.getDescriptor();
    }
    
    static {
      smarkets.eto.EtoPiqi.internalForceInit();
    }
  }
  
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse() {}
    
    private static final LoginResponse defaultInstance = new LoginResponse();
    public static LoginResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_LoginResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_LoginResponse_fieldAccessorTable;
    }
    
    // required string session = 1;
    public static final int SESSION_FIELD_NUMBER = 1;
    private boolean hasSession;
    private java.lang.String session_ = "";
    public boolean hasSession() { return hasSession; }
    public java.lang.String getSession() { return session_; }
    
    // optional uint64 reset = 2;
    public static final int RESET_FIELD_NUMBER = 2;
    private boolean hasReset;
    private long reset_ = 0L;
    public boolean hasReset() { return hasReset; }
    public long getReset() { return reset_; }
    
    public final boolean isInitialized() {
      if (!hasSession) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasSession()) {
        output.writeString(1, getSession());
      }
      if (hasReset()) {
        output.writeUInt64(2, getReset());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSession()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getSession());
      }
      if (hasReset()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, getReset());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smarkets.eto.EtoPiqi.LoginResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private smarkets.eto.EtoPiqi.LoginResponse result;
      
      // Construct using smarkets.eto.EtoPiqi.LoginResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new smarkets.eto.EtoPiqi.LoginResponse();
        return builder;
      }
      
      protected smarkets.eto.EtoPiqi.LoginResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new smarkets.eto.EtoPiqi.LoginResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smarkets.eto.EtoPiqi.LoginResponse.getDescriptor();
      }
      
      public smarkets.eto.EtoPiqi.LoginResponse getDefaultInstanceForType() {
        return smarkets.eto.EtoPiqi.LoginResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public smarkets.eto.EtoPiqi.LoginResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private smarkets.eto.EtoPiqi.LoginResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public smarkets.eto.EtoPiqi.LoginResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        smarkets.eto.EtoPiqi.LoginResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smarkets.eto.EtoPiqi.LoginResponse) {
          return mergeFrom((smarkets.eto.EtoPiqi.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smarkets.eto.EtoPiqi.LoginResponse other) {
        if (other == smarkets.eto.EtoPiqi.LoginResponse.getDefaultInstance()) return this;
        if (other.hasSession()) {
          setSession(other.getSession());
        }
        if (other.hasReset()) {
          setReset(other.getReset());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setSession(input.readString());
              break;
            }
            case 16: {
              setReset(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // required string session = 1;
      public boolean hasSession() {
        return result.hasSession();
      }
      public java.lang.String getSession() {
        return result.getSession();
      }
      public Builder setSession(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSession = true;
        result.session_ = value;
        return this;
      }
      public Builder clearSession() {
        result.hasSession = false;
        result.session_ = getDefaultInstance().getSession();
        return this;
      }
      
      // optional uint64 reset = 2;
      public boolean hasReset() {
        return result.hasReset();
      }
      public long getReset() {
        return result.getReset();
      }
      public Builder setReset(long value) {
        result.hasReset = true;
        result.reset_ = value;
        return this;
      }
      public Builder clearReset() {
        result.hasReset = false;
        result.reset_ = 0L;
        return this;
      }
    }
    
    static {
      smarkets.eto.EtoPiqi.getDescriptor();
    }
    
    static {
      smarkets.eto.EtoPiqi.internalForceInit();
    }
  }
  
  public static final class Logout extends
      com.google.protobuf.GeneratedMessage {
    // Use Logout.newBuilder() to construct.
    private Logout() {}
    
    private static final Logout defaultInstance = new Logout();
    public static Logout getDefaultInstance() {
      return defaultInstance;
    }
    
    public Logout getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Logout_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return smarkets.eto.EtoPiqi.internal_static_smarkets_eto_Logout_fieldAccessorTable;
    }
    
    // optional .smarkets.eto.LogoutReason reason = 1;
    public static final int REASON_FIELD_NUMBER = 1;
    private boolean hasReason;
    private smarkets.eto.EtoPiqi.LogoutReason reason_ = smarkets.eto.EtoPiqi.LogoutReason.LOGOUT_NONE;
    public boolean hasReason() { return hasReason; }
    public smarkets.eto.EtoPiqi.LogoutReason getReason() { return reason_; }
    
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasReason()) {
        output.writeEnum(1, getReason().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasReason()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, getReason().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static smarkets.eto.EtoPiqi.Logout parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeDelimitedFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static smarkets.eto.EtoPiqi.Logout parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(smarkets.eto.EtoPiqi.Logout prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private smarkets.eto.EtoPiqi.Logout result;
      
      // Construct using smarkets.eto.EtoPiqi.Logout.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new smarkets.eto.EtoPiqi.Logout();
        return builder;
      }
      
      protected smarkets.eto.EtoPiqi.Logout internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new smarkets.eto.EtoPiqi.Logout();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return smarkets.eto.EtoPiqi.Logout.getDescriptor();
      }
      
      public smarkets.eto.EtoPiqi.Logout getDefaultInstanceForType() {
        return smarkets.eto.EtoPiqi.Logout.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public smarkets.eto.EtoPiqi.Logout build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private smarkets.eto.EtoPiqi.Logout buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public smarkets.eto.EtoPiqi.Logout buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        smarkets.eto.EtoPiqi.Logout returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof smarkets.eto.EtoPiqi.Logout) {
          return mergeFrom((smarkets.eto.EtoPiqi.Logout)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(smarkets.eto.EtoPiqi.Logout other) {
        if (other == smarkets.eto.EtoPiqi.Logout.getDefaultInstance()) return this;
        if (other.hasReason()) {
          setReason(other.getReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              smarkets.eto.EtoPiqi.LogoutReason value = smarkets.eto.EtoPiqi.LogoutReason.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                setReason(value);
              }
              break;
            }
          }
        }
      }
      
      
      // optional .smarkets.eto.LogoutReason reason = 1;
      public boolean hasReason() {
        return result.hasReason();
      }
      public smarkets.eto.EtoPiqi.LogoutReason getReason() {
        return result.getReason();
      }
      public Builder setReason(smarkets.eto.EtoPiqi.LogoutReason value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasReason = true;
        result.reason_ = value;
        return this;
      }
      public Builder clearReason() {
        result.hasReason = false;
        result.reason_ = smarkets.eto.EtoPiqi.LogoutReason.LOGOUT_NONE;
        return this;
      }
    }
    
    static {
      smarkets.eto.EtoPiqi.getDescriptor();
    }
    
    static {
      smarkets.eto.EtoPiqi.internalForceInit();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smarkets_eto_Payload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smarkets_eto_Payload_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smarkets_eto_Replay_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smarkets_eto_Replay_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smarkets_eto_Login_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smarkets_eto_Login_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smarkets_eto_LoginResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smarkets_eto_LoginResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_smarkets_eto_Logout_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_smarkets_eto_Logout_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016eto.piqi.proto\022\014smarkets.eto\"\376\001\n\007Paylo" +
      "ad\022\013\n\003seq\030\001 \002(\004\022\'\n\004type\030\002 \001(\0162\031.smarkets" +
      ".eto.PayloadType\022\030\n\tis_replay\030\003 \001(\010:\005fal" +
      "se\022$\n\006replay\030\004 \001(\0132\024.smarkets.eto.Replay" +
      "\022\"\n\005login\030\005 \001(\0132\023.smarkets.eto.Login\0223\n\016" +
      "login_response\030\006 \001(\0132\033.smarkets.eto.Logi" +
      "nResponse\022$\n\006logout\030\007 \001(\0132\024.smarkets.eto" +
      ".Logout\"\025\n\006Replay\022\013\n\003seq\030\001 \002(\004\"\030\n\005Login\022" +
      "\017\n\007session\030\001 \002(\t\"/\n\rLoginResponse\022\017\n\007ses" +
      "sion\030\001 \002(\t\022\r\n\005reset\030\002 \001(\004\"4\n\006Logout\022*\n\006r",
      "eason\030\001 \001(\0162\032.smarkets.eto.LogoutReason*" +
      "\306\001\n\013PayloadType\022\020\n\014PAYLOAD_NONE\020\001\022\020\n\014PAY" +
      "LOAD_PING\020\002\022\020\n\014PAYLOAD_PONG\020\003\022\023\n\017PAYLOAD" +
      "_GAPFILL\020\004\022\025\n\021PAYLOAD_HEARTBEAT\020\005\022\022\n\016PAY" +
      "LOAD_REPLAY\020\006\022\021\n\rPAYLOAD_LOGIN\020\007\022\032\n\026PAYL" +
      "OAD_LOGIN_RESPONSE\020\010\022\022\n\016PAYLOAD_LOGOUT\020\t" +
      "*\220\001\n\014LogoutReason\022\017\n\013LOGOUT_NONE\020\001\022\034\n\030LO" +
      "GOUT_HEARTBEAT_TIMEOUT\020\002\022\027\n\023LOGOUT_CONFI" +
      "RMATION\020\003\022\030\n\024LOGOUT_LOGIN_TIMEOUT\020\004\022\036\n\032L" +
      "OGOUT_LOGIN_NOT_FIRST_SEQ\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_smarkets_eto_Payload_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_smarkets_eto_Payload_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smarkets_eto_Payload_descriptor,
              new java.lang.String[] { "Seq", "Type", "IsReplay", "Replay", "Login", "LoginResponse", "Logout", },
              smarkets.eto.EtoPiqi.Payload.class,
              smarkets.eto.EtoPiqi.Payload.Builder.class);
          internal_static_smarkets_eto_Replay_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_smarkets_eto_Replay_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smarkets_eto_Replay_descriptor,
              new java.lang.String[] { "Seq", },
              smarkets.eto.EtoPiqi.Replay.class,
              smarkets.eto.EtoPiqi.Replay.Builder.class);
          internal_static_smarkets_eto_Login_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_smarkets_eto_Login_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smarkets_eto_Login_descriptor,
              new java.lang.String[] { "Session", },
              smarkets.eto.EtoPiqi.Login.class,
              smarkets.eto.EtoPiqi.Login.Builder.class);
          internal_static_smarkets_eto_LoginResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_smarkets_eto_LoginResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smarkets_eto_LoginResponse_descriptor,
              new java.lang.String[] { "Session", "Reset", },
              smarkets.eto.EtoPiqi.LoginResponse.class,
              smarkets.eto.EtoPiqi.LoginResponse.Builder.class);
          internal_static_smarkets_eto_Logout_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_smarkets_eto_Logout_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_smarkets_eto_Logout_descriptor,
              new java.lang.String[] { "Reason", },
              smarkets.eto.EtoPiqi.Logout.class,
              smarkets.eto.EtoPiqi.Logout.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
}
